name: ROS buildfarm
description: Github Action to convert ROS packages to Debian packages
author: Jochen Sprickerhof
branding:
  icon: 'package'
  color: 'green'
inputs:
  TARGET_BRANCH:
    description: The branch name that distributes the packages.
    required: true
  ROS_DISTRO:
    description: The ROS distribution codename to compile for.
    required: true
  DEB_DISTRO:
    description: The Debian/Ubuntu distribution codename to compile for.
    required: true
  REPOS_FILE:
    description: Repos file with list of repositories to package.
    required: false
    default: sources.repos
  REPOS_CONF:
    description: Repos config.
    required: true
  BUILD_DEPENDS_FILE:
    description: Repos file with list of repositories to build.
    required: false
    default: build_depends.repos
  SBUILD_CONF:
    description: Additional sbuild.conf lines. For example EXTRA_REPOSITORIES,
      or VERBOSE. See man sbuild.conf.
    required: false
  ROSDEP_SOURCE:
    description: Additional rosdep sources.
    required: false
  GITHUB_TOKEN:
    description: Set to deploy to a DEB_DISTRO-ROS_DISTRO branch in the same repo.
    required: false
    default: false
  SQUASH_HISTORY:
    description: If set to true, all previous commits on the target branch will be discarded.
    required: false
    default: false
runs:
  using: composite
  steps:
    - name: Check out the repo
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Set git config
      run: |
        git config --local --unset-all http.https://github.com/.extraheader || true
        git config --global --add url.https://x-access-token:${{ inputs.GITHUB_TOKEN }}@github.com/.insteadOf 'https://github.com/'
        git config --global --add url.https://x-access-token:${{ inputs.GITHUB_TOKEN }}@github.com/.insteadOf 'git@github.com:'
        git config --global user.name github-actions
        git config --global user.email github-actions@github.com
      shell: bash
    - name: Cache ccache
      uses: pat-s/always-upload-cache@v3
      with:
        path: /home/runner/.cache/ccache
        key: ccache-${{ inputs.ROS_DISTRO }}-${{ github.sha }}-${{ github.run_id }}
        restore-keys: |
          ccache-${{ inputs.ROS_DISTRO }}-${{ github.sha }}
          ccache-${{ inputs.ROS_DISTRO }}
    - name: Setup build environment
      run: $GITHUB_ACTION_PATH/prepare.sh
      shell: sh
      env:
        TARGET_BRANCH: ${{ inputs.TARGET_BRANCH }}
        DEB_DISTRO: ${{ inputs.DEB_DISTRO }}
        REPOS_FILE: ${{ inputs.REPOS_FILE }}
        REPOS_CONF: ${{ inputs.REPOS_CONF }}
        SBUILD_CONF: ${{ inputs.SBUILD_CONF }}
    - name: Create packages
      run: $GITHUB_ACTION_PATH/build.sh
      shell: sh
      env:
        ROS_DISTRO: ${{ inputs.ROS_DISTRO }}
        DEB_DISTRO: ${{ inputs.DEB_DISTRO }}
        ROSDEP_SOURCE: ${{ inputs.ROSDEP_SOURCE }}
        BUILD_DEPENDS_FILE: ${{ inputs.BUILD_DEPENDS_FILE }}
    - name: Create apt repository
      run: $GITHUB_ACTION_PATH/repository.sh
      shell: sh
      env:
        ROS_DISTRO: ${{ inputs.ROS_DISTRO }}
        DEB_DISTRO: ${{ inputs.DEB_DISTRO }}
    - name: Deploy
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        file_pattern: "dists rosdep"
        commit_message: "test release"
        branch: ${{ inputs.TARGET_BRANCH }}
